import { useContext, useState } from "react";
import { AppContext } from "../components/Store";
import Head from "next/head";
import Image from "next/image";
import Nav from "./Nav";
import Footer from "./Footer";
import Chat from "./Chat";

function Layout({children, title}) {
  const {dispatch, state} = useContext(AppContext);
  const {chatVisible, chatSign} = state;

  const HandleNavOff = () => {
    dispatch({ type: "MENUOFF" });
  };

  const HandleCallSign = () => {
    let signMessage = "START A LIVE CHAT";
    dispatch({type: "ADDCHATSIGN", payload: signMessage})
  }

  const ResetCallSign =() => {
    dispatch({type: "REMOVECHATSIGN"})
  }

  const HandleShowChat = () => {
    dispatch({type: "CHATVISIBILITY"})
  }



  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav
          className="sticky top-0 bg-white flex justify-between items-center p-5"
          onMouseOver={HandleNavOff}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="40"
            height="30"
            fill="currentColor"
            className="bi bi-list md:hidden"
            viewBox="0 0 16 16"
          >
            <path
              fill-rule="evenodd"
              d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"
            />
          </svg>
          <Image
            src="/logo.svg"
            alt="logo"
            className="md:w-52 mx-auto md:mx-0"
            width={100}
            height={60}
          />
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="40"
            height="30"
            fill="currentColor"
            className="bi bi-box-arrow-in-right md:hidden"
            viewBox="0 0 16 16"
          >
            <path
              fill-rule="evenodd"
              d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"
            />
            <path
              fill-rule="evenodd"
              d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"
            />
          </svg>
          <div className="hidden md:flex items-center w-2/6 justify-evenly">
            <span>
              <button className="hidden md:block bg-blue-700 font-bold text-xl text-white rounded-full p-3 px-8">
                OPEN ACCOUNT
              </button>
            </span>
            <span>
              <button className="hidden md:block bg-slate-200 font-bold text-xl text-blue-700 rounded-full p-3 px-10">
                LOG IN
              </button>
            </span>
            <span>
              <Image
                className="hidden md:flex rounded cursor-pointer"
                src="/flag.svg"
                width={30}
                height={10}
                alt="flag"
              />
            </span>
          </div>
        </nav>
        <hr />
        <Nav handleNavOff={HandleNavOff} />
      </header>
      <main onMouseOver={HandleNavOff}>{children}</main>
      <hr className="hidden md:block" />
      <footer className="md:px-16 p-6">
        <Footer />
      </footer>
      {!chatVisible ? (
        <div
          className="hidden md:flex justify-evenly items-center fixed bottom-0 right-0 bg-blue-700 w-20 p-5 m-5 rounded-full cursor-pointer hover:w-72 hover:h-20 duration-200"
          onMouseEnter={HandleCallSign}
          onMouseLeave={ResetCallSign}
          onClick={HandleShowChat}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="40"
            height="40"
            fill="currentColor"
            className="bi bi-headset text-white"
            viewBox="0 0 16 16"
          >
            <path d="M8 1a5 5 0 0 0-5 5v1h1a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V6a6 6 0 1 1 12 0v6a2.5 2.5 0 0 1-2.5 2.5H9.366a1 1 0 0 1-.866.5h-1a1 1 0 1 1 0-2h1a1 1 0 0 1 .866.5H11.5A1.5 1.5 0 0 0 13 12h-1a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1h1V6a5 5 0 0 0-5-5z" />
          </svg>
          <p className="text-white font-bold">{chatSign}</p>
        </div>
      ) : (
        <Chat />
      )}
    </div>
  );
}

export default Layout
